export type TClient = {
  CNPJ: string;
  Fantasia: string;
  Razao: string;
  email: string;
  id: number;
  estadual: string;
  municipal: string;
  resp_cep: string;
  resp_comp: string;
  resp_cpf: string;
  resp_endereco: string;
  resp_bairro: string;
  resp_pes: string;
  resp_tel: string;
  resp_cel: string;
  resp_email: string;
  resp_city: string;
  resp_uf: string;
  resp_numero: string;
  activeClient: boolean;
  resp_obs: string;
};
